### ISSUE TITLE
"Invalid date" message

### ISSUE THREAD

**Issue by happydemic** [musicpro/temps#1]
Reposted from https://github.com/jackd248/temps/issues/49#issuecomment-552413897.

I am getting an "invalid date" message on v0.7.3.
![Invalid date - Temps](https://user-images.githubusercontent.com/12738878/68650549-2b7ca180-051d-11ea-92e3-132357622d4d.png)

You mentioned that you had to turn off time zone API requests. IP-API provides the location and time zone of an IP address without a key, if that helps?

Or if you want to use a different service, you could require users to provide their own geolocation API key, just like users currently have to provide a key for openweathermap?

**Comment by musicpro** [comment]
That is looking really good. But for me in my office I noticed that the response I am getting is a different city. So basically this is just a small thing we have to live with I guess.  What will work all the time, is the manual search for a place anyway.

So I am working a lot these times but I will try to provide a new version soon. 
Thanks for your help!!

**Comment by musicpro** [comment]
I published a new version with fixes for the problems. For me it is working, hope for you too!

**Comment by happydemic** [comment]
Perfect - thank you so much! 
And the version number appears correctly now on the settings screen as well. :)
